version: '3.4'

services:
  poc-nosql-mysql:
    image: ${DOCKER_REGISTRY-}pocnosqlmysql
    build:
      context: .
      dockerfile: Poc-NoSql-MySql/Dockerfile
    depends_on: 
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    ports:
      - "6379:6379"
